server {
    server_name guangwei.cloud www.guangwei.cloud;
    root /var/www/guangwei_cloud/landing;
    index index.html;

    location ~* ^/wp-(admin|login|content|includes|json|cron|config|trackback|comments|xmlrpc|signup|activate|mail|register)/ {
        return 444;
    }
    location ~* ^/(xmlrpc|wp-login|wp-signup|wp-cron|wp-config|wp-activate|wp-mail|wp-register)\.php {
        return 444;
    }

    location /namebar/ {
        proxy_pass http://localhost:3003/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /live/ {
        proxy_pass http://localhost:3006/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/guangwei.cloud-0001/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/guangwei.cloud-0001/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
server {
    if ($host = www.guangwei.cloud) {
        return 301 https://$host$request_uri;
    }
    if ($host = guangwei.cloud) {
        return 301 https://$host$request_uri;
    }
    listen 80;
    server_name guangwei.cloud www.guangwei.cloud;
    return 404;
}
